// frontend/src/components/organisms/Clock.tsx
import React, { useRef, useEffect } from 'react'
import { Jam } from 'types/Jam'
import moment from 'moment'

type Props = {
  jam: Jam
  height?: number
  width?: number
  popout?: boolean
}
export const Clock = ({ jam, width = 200, height = 200, popout }: Props) => {
  // use jamContext
  const canvasRef = useRef<HTMLCanvasElement | null>(null)

  useEffect(() => {
    if (!canvasRef.current) return
    canvasRef.current.width = width
    canvasRef.current.height = height

    const draw = () => {
      if (!ctx || !canvasRef.current || !jam.started_at) return

      const started_at = moment(jam.started_at)
      const currentTime = +moment()
      const endTime = started_at.clone().add(jam.time_limit, 'minutes')

      const elapsed = currentTime - +started_at // ms
      const total = +endTime - +started_at // ms
      const remaining = total - elapsed // ms

      const u = remaining / total // percent

      const secondsRemaining = remaining / 1000

      const minute = (secondsRemaining % 60) / 60
      const second = secondsRemaining % 1

      const w = width / 2
      const h = height / 2
      const hr = w * 0.8
      const mr = w * 0.6
      const sr = w * 0.4

      const ru = Math.abs(u - 1)

      const sat = ru * 100
      const hue = Math.abs(u * 30)

      ctx.save()

      ctx.clearRect(0, 0, width, height)
      ctx.translate(w, h)
      ctx.rotate(Math.PI / 2)

      ctx.lineWidth = width / 10

      ctx.strokeStyle = `hsl(${hue}, ${sat}%, 30%)`
      ctx.beginPath()
      ctx.arc(0, 0, hr, 0, u * Math.PI * 2)
      ctx.stroke()

      ctx.strokeStyle = `hsl(${hue}, ${sat}%, 50%)`
      ctx.beginPath()
      ctx.arc(0, 0, mr, 0, minute * Math.PI * 2)
      ctx.stroke()

      ctx.beginPath()
      const s = Math.abs(1 - second * second * second * 0.5)
      ctx.fillStyle = `hsl(${hue}, ${sat}%, ${s * 100}%)`
      ctx.arc(0, 0, sr + width / 20, 0, Math.PI * 2)
      ctx.fill()

      ctx.restore()

      ctx.fillStyle = '#333'
      ctx.font = 'small-caps bold 24px/1 sans-serif'

      const minutes = Math.floor(secondsRemaining / 60)
      const seconds = Math.floor(secondsRemaining % 60)

      ctx.textAlign = 'center'
      ctx.textBaseline = 'middle'

      ctx.fillText(`${minutes}:${seconds}`, width / 2, height / 2)

      document.title = `[${minutes}:${seconds}] remaining!!`
    }

    const ctx = canvasRef.current.getContext('2d')

    const interval = setInterval(() => {
      draw()
    }, 1000 / 15)

    return () => {
      clearInterval(interval)
    }
  }, [canvasRef, width, height, jam.started_at, jam.time_limit])

  return <canvas ref={canvasRef} />
}

// src/components/Clock.svelte
<script>
  import { onMount } from "svelte";
  const width = 300;
  const height = 300;

  export let total;
  export let startedAt;
  let canvas;
  let ctx;

  $: current = new Date() / 1000;
  $: started = new Date(startedAt) / 1000;
  $: remaining = started - current + total;

  const draw = () => {
    const u = 1 - remaining / total;
    const minute = Math.abs(1 - (remaining % 60) / 60);
    const second = Math.abs(1 - (remaining % 1));
    const w = width / 2;
    const h = height / 2;
    const hr = w * 0.9;
    const mr = w * 0.8;
    const sr = w * 0.7;

    const warning = u > 0.8;

    if (warning) {
      const flicker = Math.sin(u * Math.PI * 2 * total);
      if (flicker > 0) {
        document.title = "WARNING";
      } else {
        document.title = "Jam Ending";
      }
    }

    ctx.save();
    ctx.fillStyle = "#fff8";
    ctx.fillRect(0, 0, width, height);

    ctx.translate(w, h);
    ctx.rotate(Math.PI / 2);

    ctx.lineWidth = 5;

    // ctx.strokeStyle = `hsl()`;
    ctx.strokeStyle = warning ? "#f33" : "#333";
    ctx.beginPath();
    ctx.arc(0, 0, hr, 0, u * Math.PI * 2);
    ctx.stroke();

    // ctx.strokeStyle = `hsl()`;
    ctx.strokeStyle = warning ? "#955" : "#555";
    ctx.beginPath();
    ctx.arc(0, 0, mr, 0, minute * Math.PI * 2);
    ctx.stroke();

    // ctx.strokeStyle = `hsl()`;
    ctx.strokeStyle = warning ? "#4004" : "#0004";
    ctx.beginPath();
    ctx.arc(0, 0, sr, 0, second * Math.PI * 2);
    ctx.stroke();

    ctx.restore();
  };

  onMount(() => {
    ctx = canvas.getContext("2d");

    const interval = setInterval(() => {
      current = new Date() / 1000;
      draw();
    }, 1000 / 15);

    return () => {
      clearInterval(interval);
    };
  });
</script>

<canvas bind:this={canvas} {width} {height} />

<!-- <div>
  <h3>clock</h3>
  <p>total: {total}</p>
  <p>started: {started}</p>
  <p>current: {current}</p>
  <p>remaining: {remaining}</p>
  <p>percent remaining: {remaining / total}</p>
  <p>percent elapsed: {1 - remaining / total}</p>
</div> -->
